# Generated by Django 4.2.3 on 2023-07-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_blog_deleted_at_alter_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
