# Generated by Django 4.2.3 on 2023-07-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_blog_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                default="default-blog.jpg", upload_to="blogs/images"
            ),
        ),
    ]
