# Generated by Django 4.2.3 on 2023-07-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0004_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
