# Generated by Django 4.2.3 on 2023-07-29 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0007_blog_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="published_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 29, 19, 11, 40, 570189)
            ),
        ),
    ]
