# Generated by Django 4.2.3 on 2023-07-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0008_blog_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="published_at",
            field=models.DateTimeField(),
        ),
    ]
